import { Component, inject, signal } from "@angular/core";
import { HttpClient } from "@angular/common/http";
import { FormsModule } from "@angular/forms";
import { Router, RouterLink } from "@angular/router";

type Location={id:string;name:string};
type Zone={id:string;name:string;type:string;room_id:string|null};
type Camera={id:string;name:string;provider:string;status:string;location_id:string|null;plan_zone_id:string|null;location_name:string|null;zone_name:string|null;room_name:string|null};

@Component({
  selector:"app-camera-settings",standalone:true,imports:[FormsModule,RouterLink],
  template:`
  <main><aside><h1>Q <span>QUESTCONTROL</span></h1><nav><a routerLink="/">Обзор</a><a routerLink="/bookings">Бронирования</a><a class="sessions-nav" routerLink="/sessions">Сессии</a><a routerLink="/locations">Локации</a><a routerLink="/rooms">Комнаты</a><a routerLink="/cameras">Камеры</a><a class="camera-settings-link active" routerLink="/camera-settings">Настройки камер</a><a routerLink="/inventory">Инвентарь</a><a routerLink="/users">Пользователи</a></nav></aside>
  <section><header><div><h2>Настройки камер</h2><p>Распределение всех камер аккаунта по локациям и зонам плана</p></div><div class="header-actions"><button class="tuya-sync" (click)="syncTuya()" [disabled]="syncing()">{{syncing()?"Синхронизация…":"↻ Синхронизировать с Tuya"}}</button><button class="secondary" (click)="load()">Обновить список</button></div></header>
  @if(error()){<p class="error">{{error()}}</p>}@if(notice()){<p class="notice">{{notice()}}</p>}
  <section class="headset-base-settings"><h3>Зарядная база VR-шлемов</h3><p>Прямоугольник задаётся в долях кадра: левый верхний угол и размер. Для одного стеллажа на нескольких камерах используйте одинаковый ID базы.</p><div class="base-grid"><label>Камера<select [(ngModel)]="headsetCameraId"><option value="">Выберите камеру...</option>@for(camera of cameras();track camera.id){<option [value]="camera.id">{{camera.name}}</option>}</select></label><label>Пресет PTZ<input [(ngModel)]="headsetPreset" placeholder="default" /></label><label>Левый край X<input type="number" min="0" max="1" step="0.01" [(ngModel)]="headsetX" /></label><label>Верх Y<input type="number" min="0" max="1" step="0.01" [(ngModel)]="headsetY" /></label><label>Ширина<input type="number" min="0.01" max="1" step="0.01" [(ngModel)]="headsetWidth" /></label><label>Высота<input type="number" min="0.01" max="1" step="0.01" [(ngModel)]="headsetHeight" /></label><label>ID стойки<input [(ngModel)]="baseStationId" placeholder="krampus_rack_1" /></label><label>Шлемов на базе<input type="number" min="0" max="100" [(ngModel)]="expectedHeadsetCount" /></label></div><button class="tuya-sync" (click)="saveChargingBase()" [disabled]="savingBase()||!headsetCameraId">{{savingBase()?"Сохранение…":"Сохранить CHARGING_BASE"}}</button></section>
  <div class="camera-table"><div class="table-head"><span>Камера</span><span>Локация</span><span>Зона или комната на плане</span><span></span></div>
  @for(camera of cameras();track camera.id){<article>
    <div class="camera-name"><i [class.online]="camera.status==='ONLINE'"></i><span><b>{{camera.name}}</b><small>{{camera.provider}} · {{camera.status}}</small></span></div>
    <select [ngModel]="camera.location_id||''" (ngModelChange)="locationChanged(camera,$event)">@if(isOwner()){<option value="">Не назначена</option>}@else if(!camera.location_id){<option value="" disabled>Выберите локацию</option>}@for(location of locations();track location.id){<option [value]="location.id">{{location.name}}</option>}</select>
    <select [disabled]="!camera.location_id||loadingZones().includes(camera.location_id)" [ngModel]="camera.plan_zone_id||''" (ngModelChange)="zoneChanged(camera,$event)"><option value="">Без зоны</option>@for(zone of zonesFor(camera.location_id);track zone.id){<option [value]="zone.id">{{zone.name}} · {{zoneType(zone.type)}}@if(zone.room_id){ · квест-комната}</option>}</select>
    <div class="assignment">@if(camera.zone_name){<b>{{camera.zone_name}}</b><small>{{camera.room_name||"Обычная зона плана"}}</small>}@else if(camera.location_name){<span>Только локация</span>}@else{<span>Не распределена</span>}</div>
  </article>}@empty{<div class="empty"><b>Камер в аккаунте пока нет</b><span>Выполните синхронизацию Tuya на вкладке камер.</span></div>}</div>
  </section></main>`,
  styles:[`
    .camera-settings-link{margin:2px 0 6px!important}
    .header-actions{display:flex;gap:10px;align-items:center}.tuya-sync{background:#4058df;color:#fff}.secondary{background:#eef1f6;color:#344054;box-shadow:none}.notice{padding:12px 14px;border-radius:8px;background:#ecfdf3;color:#067647}.headset-base-settings{margin-top:24px;padding:18px;border:1px solid #c7d7fe;border-radius:14px;background:#f7f9ff}.headset-base-settings h3{margin:0 0 5px}.headset-base-settings p{margin:0 0 14px;color:var(--muted);font-size:12px}.base-grid{display:grid;grid-template-columns:repeat(4,minmax(120px,1fr));gap:12px;margin-bottom:14px}.base-grid label{display:grid;gap:5px;font-size:12px;font-weight:700}.base-grid input,.base-grid select{width:100%;padding:9px;box-sizing:border-box}.camera-table{margin-top:24px;overflow:hidden;border:1px solid var(--line);border-radius:14px;background:#fff}.table-head,.camera-table article{display:grid;grid-template-columns:minmax(190px,1.2fr) minmax(170px,.8fr) minmax(230px,1.1fr) minmax(150px,.7fr);gap:14px;align-items:center;padding:14px 16px}.table-head{background:#f7f8fb;color:var(--muted);font-size:11px;font-weight:700}.camera-table article{border-top:1px solid #edf0f4}.camera-name{display:flex;align-items:center;gap:10px;min-width:0}.camera-name i{width:9px;height:9px;border-radius:50%;background:#98a2b3}.camera-name i.online{background:#079455}.camera-name b,.camera-name small,.assignment b,.assignment small{display:block}.camera-name small,.assignment small,.assignment span{margin-top:3px;color:var(--muted);font-size:10px}.camera-table select{width:100%;min-width:0;padding:9px}.empty{margin:0;border:0}@media(max-width:900px){header{align-items:flex-start}.header-actions{width:100%;flex-wrap:wrap}.table-head{display:none}.camera-table article{grid-template-columns:1fr}.assignment{padding-top:5px}.base-grid{grid-template-columns:repeat(2,minmax(120px,1fr))}}@media(max-width:600px){.camera-table article{padding:16px 14px}.header-actions{display:grid;grid-template-columns:1fr}.header-actions button{width:100%}.base-grid{grid-template-columns:1fr}}
  `]
})
export class CameraSettingsComponent{
  private http=inject(HttpClient);private router=inject(Router);
  cameras=signal<Camera[]>([]);locations=signal<Location[]>([]);zones=signal<Record<string,Zone[]>>({});loadingZones=signal<string[]>([]);syncing=signal(false);error=signal("");notice=signal("");
  headsetCameraId="";headsetPreset="default";headsetX=0;headsetY=0;headsetWidth=0.2;headsetHeight=0.2;baseStationId="krampus_rack_1";expectedHeadsetCount=4;savingBase=signal(false);
  constructor(){if(!this.canConfigure()){void this.router.navigateByUrl("/cameras");return}this.http.get<Location[]>("/api/locations").subscribe({next:l=>this.locations.set(l)});this.load()}
  isOwner(){try{return JSON.parse(atob((sessionStorage.getItem("access_token")||"").split(".")[1])).role==="OWNER"}catch{return false}}
  canConfigure(){try{return ["OWNER","ADMIN"].includes(JSON.parse(atob((sessionStorage.getItem("access_token")||"").split(".")[1])).role)}catch{return false}}
  load(){this.http.get<Camera[]>("/api/camera-settings").subscribe({next:c=>{this.cameras.set(c);for(const id of new Set(c.map(x=>x.location_id).filter((x):x is string=>!!x)))this.loadZones(id)},error:()=>this.error.set("Не удалось загрузить настройки камер.")})}
  loadZones(locationId:string){if(this.zones()[locationId]||this.loadingZones().includes(locationId))return;this.loadingZones.update(v=>[...v,locationId]);this.http.get<{zones:Zone[]}>(`/api/locations/${locationId}/plan`).subscribe({next:p=>{this.zones.update(v=>({...v,[locationId]:p.zones}));this.loadingZones.update(v=>v.filter(id=>id!==locationId))},error:()=>this.loadingZones.update(v=>v.filter(id=>id!==locationId))})}
  zonesFor(locationId:string|null){return locationId?this.zones()[locationId]||[]:[]}
  locationChanged(camera:Camera,locationId:string){camera.location_id=locationId||null;camera.plan_zone_id=null;if(locationId)this.loadZones(locationId);this.save(camera)}
  zoneChanged(camera:Camera,zoneId:string){camera.plan_zone_id=zoneId||null;this.save(camera)}
  save(camera:Camera){this.error.set("");this.http.patch(`/api/cameras/${camera.id}/assignment`,{locationId:camera.location_id,zoneId:camera.plan_zone_id}).subscribe({next:()=>{this.notice.set(`Камера «${camera.name}» распределена.`);this.load()},error:()=>{this.error.set("Не удалось сохранить привязку камеры.");this.load()}})}
  saveChargingBase(){this.savingBase.set(true);this.error.set("");this.notice.set("");this.http.post(`/api/cameras/${this.headsetCameraId}/headset/zones`,{presetName:this.headsetPreset||"default",name:"Зарядная стойка VR",zoneType:"CHARGING_BASE",x:Number(this.headsetX),y:Number(this.headsetY),width:Number(this.headsetWidth),height:Number(this.headsetHeight),baseStationId:this.baseStationId||"krampus_rack_1",expectedHeadsetCount:Number(this.expectedHeadsetCount),enabled:true}).subscribe({next:()=>{this.savingBase.set(false);this.notice.set("Зона зарядной базы сохранена.")},error:(e)=>{this.savingBase.set(false);this.error.set(e?.error?.message||"Не удалось сохранить зону зарядной базы.")}})}
  syncTuya(){this.syncing.set(true);this.error.set("");this.notice.set("");this.http.post<{cameras:number;created:number}>("/api/cameras/sync/tuya",{}).subscribe({next:r=>{this.syncing.set(false);this.notice.set(`Синхронизация завершена: камер ${r.cameras}, добавлено ${r.created}.`);this.load()},error:()=>{this.syncing.set(false);this.error.set("Не удалось синхронизировать камеры с Tuya.")}})}
  zoneType(type:string){return({GAME:"Игровая",VR:"VR",CORRIDOR:"Коридор",RECEPTION:"Ресепшен",LOCKERS:"Шкафчики",TECHNICAL:"Техническая",STORAGE:"Склад",RESTROOM:"Санузел",OTHER:"Другая"} as Record<string,string>)[type]||type}
}
