import { Component, inject, signal } from "@angular/core";
import { DatePipe } from "@angular/common";
import { FormsModule } from "@angular/forms";
import { HttpClient } from "@angular/common/http";
import { RouterLink } from "@angular/router";
import { forkJoin } from "rxjs";

type User={id:string;display_name:string;is_active:boolean};
type Location={id:string;name:string};
type Shift={id:string;user_id:string;user_name:string;location_id:string;location_name:string;starts_at:string;ends_at:string;responsibility:string};

@Component({selector:"app-work-schedules",standalone:true,imports:[FormsModule,RouterLink,DatePipe],template:`
<main><aside><h1>Q <span>QUESTCONTROL</span></h1><nav><a routerLink="/">Обзор</a><a routerLink="/bookings">Бронирования</a><a class="active" routerLink="/work-schedules">Графики работы</a><a routerLink="/locations">Локации</a><a routerLink="/rooms">Комнаты</a><a routerLink="/cameras">Камеры</a><a routerLink="/inventory">Инвентарь</a><a routerLink="/users">Пользователи</a></nav></aside>
<section><header><div><h2>Графики работы</h2><p>Кто, когда и за что отвечает на каждой локации</p></div><button class="new-routine" (click)="modalOpen.set(true)">＋ Новый график</button></header>
<div class="schedule-toolbar"><div class="week-nav"><button (click)="moveWeek(-7)">←</button><b>{{weekLabel()}}</b><button (click)="moveWeek(7)">→</button></div><button class="today" (click)="goToday()">Сегодня</button></div>
@if(notice()){<p class="notice">{{notice()}}</p>}
@if(error()){<p class="error">{{error()}}</p>}
<div class="week-grid">@for(day of days();track day.key){<section class="day" [class.today]="day.today"><header><b>{{dayTitle(day.date)}}</b><span>{{dayDate(day.date)}}</span></header><div class="shifts">@for(s of shiftsFor(day.key);track s.id){<article><div><b>{{s.user_name}}</b><span>{{s.starts_at|date:'HH:mm'}}–{{s.ends_at|date:'HH:mm'}} · {{s.location_name}}</span><strong>{{s.responsibility}}</strong></div><button aria-label="Удалить смену" (click)="remove(s)">×</button></article>}@empty{<p>Смен нет</p>}</div></section>}</div>
</section></main>
@if(modalOpen()){<div class="routine-backdrop" (click)="modalOpen.set(false)"><section class="routine-dialog" role="dialog" aria-modal="true" aria-labelledby="routine-title" (click)="$event.stopPropagation()"><header><div><span>▣</span><h3 id="routine-title">Новый график</h3></div><button aria-label="Закрыть" (click)="modalOpen.set(false)">×</button></header><div class="mode-switch"><button [class.active]="recurring" (click)="recurring=true">Повторяющийся</button><button [class.active]="!recurring" (click)="recurring=false">Одна смена</button></div>
<form (ngSubmit)="addShift()"><label>Сотрудник<select name="user" [(ngModel)]="userId" required><option value="">Выберите сотрудника</option>@for(u of users();track u.id){<option [value]="u.id">{{u.display_name}}</option>}</select></label><label>Локация<select name="location" [(ngModel)]="locationId" required><option value="">Выберите локацию</option>@for(l of locations();track l.id){<option [value]="l.id">{{l.name}}</option>}</select></label><label class="responsibility">За что отвечает<input name="responsibility" [(ngModel)]="responsibility" placeholder="Например: ресепшен, VR-зона" required></label>
@if(recurring){<div class="weekday-block"><div><span>Дни недели</span><div class="quick-days"><button type="button" (click)="setWeekdays([1,2,3,4,5])">Будни</button><button type="button" (click)="setWeekdays([6,7])">Выходные</button><button type="button" (click)="setWeekdays([1,2,3,4,5,6,7])">Каждый день</button></div></div><div class="weekday-picker">@for(day of weekdayOptions;track day.value){<button type="button" [class.active]="weekdays.includes(day.value)" (click)="toggleWeekday(day.value)">{{day.label}}</button>}</div></div><div class="two-cols"><label>Период с<input name="repeatFrom" type="date" [(ngModel)]="repeatFrom" required></label><label>По<input name="repeatTo" type="date" [(ngModel)]="repeatTo" required></label></div><div class="two-cols"><label>Начало<input name="startTime" type="time" [(ngModel)]="startTime" required></label><label>Конец<input name="endTime" type="time" [(ngModel)]="endTime" required></label></div>}@else{<div class="two-cols"><label>Начало<input name="start" type="datetime-local" [(ngModel)]="startsAt" required></label><label>Конец<input name="end" type="datetime-local" [(ngModel)]="endsAt" required></label></div>}
<footer><button type="button" class="cancel" (click)="modalOpen.set(false)">Отмена</button><button [disabled]="saving()">{{saving()?"Сохраняем…":recurring?"Создать график":"Добавить смену"}}</button></footer></form></section></div>}
`,styles:[`
.new-routine{font-size:13px}.schedule-toolbar{display:flex;align-items:center;justify-content:center;gap:10px;margin-top:24px}.week-nav{display:flex;align-items:center;gap:12px}.week-nav button,.schedule-toolbar .today{padding:8px 12px;box-shadow:none}.week-nav b{min-width:170px;text-align:center}.schedule-toolbar .today{background:#eef0ff;color:var(--primary)}.notice{color:var(--success);font-weight:700}.week-grid{display:grid;grid-template-columns:repeat(7,minmax(155px,1fr));gap:10px;margin-top:18px;overflow-x:auto}.day{min-height:360px;border:1px solid var(--line);border-radius:14px;background:#fff}.day.today{border-color:#7c83ff;box-shadow:0 0 0 2px #7c83ff22}.day>header{display:flex;justify-content:space-between;padding:13px;border-bottom:1px solid var(--line);text-transform:capitalize}.day>header span{color:var(--muted)}.shifts{display:grid;gap:8px;padding:9px}.shifts article{display:flex;align-items:start;gap:5px;padding:11px;border-radius:10px;background:#f3f4ff;border-left:3px solid var(--primary)}.shifts article div{min-width:0;flex:1}.shifts b,.shifts span,.shifts strong{display:block}.shifts span{margin:4px 0;color:var(--muted);font-size:10px}.shifts strong{overflow-wrap:anywhere;font-size:11px}.shifts button{padding:2px 6px;background:transparent;box-shadow:none;color:#98a2b3;font-size:18px}.shifts>p{color:var(--muted);font-size:11px;text-align:center}.error{color:var(--danger)}
.routine-backdrop{position:fixed;z-index:1100;inset:0;display:grid;place-items:center;padding:20px;background:#111827a6;backdrop-filter:blur(7px)}.routine-dialog{width:min(680px,100%);max-height:calc(100vh - 30px);overflow:auto;padding:28px;border:1px solid #ffffff18;border-radius:24px;background:#202124;color:#f5f5f5;box-shadow:0 30px 100px #0008}.routine-dialog>header{display:flex;align-items:center;justify-content:space-between;padding-bottom:20px;border-bottom:1px solid #ffffff10}.routine-dialog>header div{display:flex;align-items:center;gap:12px}.routine-dialog h3{margin:0;font-size:22px}.routine-dialog>header span{font-size:22px}.routine-dialog>header button{padding:0;background:transparent;box-shadow:none;color:#aeb6c6;font-size:30px}.mode-switch{display:grid;grid-template-columns:1fr 1fr;gap:4px;margin:20px 0;padding:4px;border-radius:14px;background:#111214}.mode-switch button{background:transparent;box-shadow:none;color:#aaa}.mode-switch button.active{background:#303134;color:#fff}.routine-dialog form{display:grid!important;grid-template-columns:1fr 1fr!important;gap:16px!important;margin:0!important;padding:0!important;border:0!important;background:transparent!important;box-shadow:none!important}.routine-dialog label{color:#b8b8bb}.routine-dialog input,.routine-dialog select{border-color:#424348;background:#111214;color:#f5f5f5}.responsibility,.weekday-block,.two-cols,.routine-dialog footer{grid-column:1/-1}.weekday-block{display:grid;gap:10px}.weekday-block>div:first-child{display:flex;align-items:center;justify-content:space-between;color:#b8b8bb;font-size:12px;font-weight:700}.quick-days{display:flex;gap:6px}.quick-days button{padding:6px 10px;background:#111214;box-shadow:none;color:#aaa}.weekday-picker{display:grid;grid-template-columns:repeat(7,1fr);gap:8px}.weekday-picker button{padding:12px 5px;border:1px solid #424348;background:#17181a;box-shadow:none;color:#aaa}.weekday-picker button.active{border-color:#fff;background:#f4f4f4;color:#14151a}.two-cols{display:grid;grid-template-columns:1fr 1fr;gap:16px}.routine-dialog footer{display:flex;justify-content:flex-end;gap:10px;margin-top:6px;padding-top:20px;border-top:1px solid #ffffff10}.routine-dialog footer .cancel{background:transparent;box-shadow:none;color:#bbb}@media(max-width:1100px){.week-grid{grid-template-columns:repeat(7,180px)}}@media(max-width:760px){main>section>header{display:grid!important}.schedule-toolbar{justify-content:space-between}.week-nav{gap:4px}.week-nav b{min-width:130px}.week-grid{margin-bottom:85px}.routine-dialog{padding:20px}.routine-dialog form{grid-template-columns:1fr!important}.routine-dialog label,.responsibility,.weekday-block,.two-cols,.routine-dialog footer{grid-column:1}.weekday-picker{grid-template-columns:repeat(4,1fr)}.quick-days{flex-wrap:wrap}.weekday-block>div:first-child{align-items:start;flex-direction:column;gap:8px}.two-cols{grid-template-columns:1fr}}
`]})
export class WorkSchedulesComponent{
 private http=inject(HttpClient); users=signal<User[]>([]);locations=signal<Location[]>([]);shifts=signal<Shift[]>([]);saving=signal(false);error=signal("");notice=signal("");modalOpen=signal(false);weekStart=signal(this.monday(new Date()));userId="";locationId="";startsAt="";endsAt="";responsibility="";recurring=true;repeatFrom=this.localDate(new Date());repeatTo=this.localDate(new Date());startTime="09:00";endTime="18:00";weekdays:number[]=[];weekdayOptions=[{value:1,label:"Пн"},{value:2,label:"Вт"},{value:3,label:"Ср"},{value:4,label:"Чт"},{value:5,label:"Пт"},{value:6,label:"Сб"},{value:7,label:"Вс"}];
 constructor(){forkJoin({users:this.http.get<User[]>("/api/users"),locations:this.http.get<Location[]>("/api/locations")}).subscribe({next:r=>{this.users.set(r.users.filter(u=>u.is_active));this.locations.set(r.locations);this.locationId=r.locations[0]?.id||"";this.load()},error:()=>this.error.set("Не удалось загрузить сотрудников и локации.")});}
 monday(value:Date){const d=new Date(value);d.setHours(0,0,0,0);d.setDate(d.getDate()-((d.getDay()+6)%7));return d;}
 localDate(d:Date){const copy=new Date(d.getTime()-d.getTimezoneOffset()*60000);return copy.toISOString().slice(0,10)}
 days(){return Array.from({length:7},(_,i)=>{const date=new Date(this.weekStart());date.setDate(date.getDate()+i);return{date,key:this.localDate(date),today:this.localDate(date)===this.localDate(new Date())}})}
 weekLabel(){const d=this.days();return `${d[0].date.toLocaleDateString("ru-RU",{day:"numeric",month:"short"})} — ${d[6].date.toLocaleDateString("ru-RU",{day:"numeric",month:"short"})}`}
 dayTitle(date:Date){return date.toLocaleDateString("ru-RU",{weekday:"short"})}
 dayDate(date:Date){return date.toLocaleDateString("ru-RU",{day:"numeric",month:"short"})}
 moveWeek(days:number){const d=new Date(this.weekStart());d.setDate(d.getDate()+days);this.weekStart.set(d);this.load()}
 goToday(){this.weekStart.set(this.monday(new Date()));this.load()}
 load(){const ds=this.days();this.http.get<Shift[]>(`/api/work-schedules?from=${ds[0].key}&to=${ds[6].key}`).subscribe({next:s=>this.shifts.set(s),error:()=>this.error.set("Не удалось загрузить график.")})}
 shiftsFor(day:string){return this.shifts().filter(s=>this.localDate(new Date(s.starts_at))===day)}
 toggleWeekday(day:number){this.weekdays=this.weekdays.includes(day)?this.weekdays.filter(value=>value!==day):[...this.weekdays,day].sort()}
 setWeekdays(days:number[]){this.weekdays=[...days]}
 addShift(){if(!this.userId||!this.locationId||!this.responsibility.trim())return;if(this.recurring){this.addRecurring();return}if(!this.startsAt||!this.endsAt)return;this.saving.set(true);this.error.set("");this.notice.set("");this.http.post("/api/work-schedules",{userId:this.userId,locationId:this.locationId,startsAt:new Date(this.startsAt).toISOString(),endsAt:new Date(this.endsAt).toISOString(),responsibility:this.responsibility.trim()}).subscribe({next:()=>{this.saving.set(false);this.modalOpen.set(false);this.responsibility="";this.notice.set("Смена добавлена.");this.load()},error:({status})=>{this.saving.set(false);this.error.set(status===409?"У сотрудника уже есть смена в это время.":"Не удалось добавить смену.")}})}
 addRecurring(){if(!this.repeatFrom||!this.repeatTo||!this.weekdays.length){this.error.set("Выберите период и хотя бы один день недели.");return}this.saving.set(true);this.error.set("");this.notice.set("");this.http.post<{created:number;skipped:number}>("/api/work-schedules/recurring",{userId:this.userId,locationId:this.locationId,from:this.repeatFrom,to:this.repeatTo,weekdays:this.weekdays,startsAt:this.startTime,endsAt:this.endTime,responsibility:this.responsibility.trim()}).subscribe({next:r=>{this.saving.set(false);this.modalOpen.set(false);this.notice.set(`Создано смен: ${r.created}${r.skipped?`. Пропущено пересечений: ${r.skipped}.`:"."}`);this.load()},error:()=>{this.saving.set(false);this.error.set("Не удалось создать повторяющийся график. Проверьте даты и время.")}})}
 remove(s:Shift){this.http.delete(`/api/work-schedules/${s.id}`).subscribe({next:()=>this.shifts.update(items=>items.filter(i=>i.id!==s.id)),error:()=>this.error.set("Не удалось удалить смену.")})}
}
