import { Component, inject, signal } from "@angular/core";
import { DatePipe } from "@angular/common";
import { FormsModule } from "@angular/forms";
import { HttpClient } from "@angular/common/http";
import { RouterLink } from "@angular/router";
type Location={id:string;name:string}; type Room={id:string;name:string;kind:string;capacity:number;status:string;location_id:string}; type Device={id:string;room_id:string;name:string;type:string;status:string;last_seen:string|null;agent_id:string|null};
@Component({selector:"app-rooms",standalone:true,imports:[FormsModule,RouterLink,DatePipe],template:`
<main><aside><h1>Q <span>QUESTCONTROL</span></h1><nav><a routerLink="/">Обзор</a><a routerLink="/bookings">Бронирования</a><a routerLink="/locations">Локации</a><a class="active" routerLink="/rooms">Комнаты</a><a routerLink="/cameras">Камеры</a><a routerLink="/krampus">Krampus House</a><a routerLink="/users">Пользователи</a></nav></aside>
<section><header><div><h2>Комнаты и устройства</h2><p>Состояние площадок и подключённых агентов</p></div><button (click)="showForm.set(!showForm())">{{showForm()?"Закрыть":"+ Добавить комнату"}}</button></header>
@if(showForm()){<form (ngSubmit)="create()"><label>Название<input name="name" [(ngModel)]="draft.name" required></label><label>Локация<select name="location" [(ngModel)]="draft.locationId" required>@for(l of locations();track l.id){<option [value]="l.id">{{l.name}}</option>}</select></label><label>Тип<select name="kind" [(ngModel)]="draft.kind"><option value="REAL">Реальная</option><option value="VR">VR</option></select></label><label>Вместимость<input name="capacity" type="number" min="1" [(ngModel)]="draft.capacity"></label><button>Создать</button></form>}
@if(error()){<p class="error">{{error()}}</p>}<div class="room-grid">@for(r of rooms();track r.id){<article><div class="room-head"><div><span class="eyebrow">{{r.kind}} · до {{r.capacity}} игроков</span><h3>{{r.name}}</h3></div><span class="dot" [class.online]="roomOnline(r.id)">{{roomOnline(r.id)?"ONLINE":"OFFLINE"}}</span></div><div class="devices">@for(d of roomDevices(r.id);track d.id){<div><span><b>{{d.name}}</b><small>{{d.type}} · {{d.agent_id||"без агента"}}</small></span><span><b>{{d.status}}</b><small>{{d.last_seen?(d.last_seen|date:'HH:mm:ss'):"нет heartbeat"}}</small></span></div>}@empty{<p>Устройства не привязаны</p>}</div>@if(/krampus/i.test(r.name)){<a class="room-link" routerLink="/krampus">Открыть панель Krampus →</a>}</article>}@empty{<div class="empty"><b>Комнат пока нет</b></div>}</div></section></main>`,
styles:[`.room-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px;margin-top:24px}.room-grid>article{padding:20px;background:#fff;border:1px solid var(--line);border-radius:16px}.room-head{display:flex;justify-content:space-between}.room-head h3{margin:6px 0 18px;font-size:20px}.eyebrow{color:var(--muted);font-size:11px;font-weight:700}.dot{height:max-content;padding:7px 9px;border-radius:999px;background:#feecef;color:#a62938;font-size:10px;font-weight:800}.dot.online{background:#e5f8ed;color:#087443}.devices{display:grid;gap:8px}.devices>div{display:flex;justify-content:space-between;padding:12px;background:#f8f9fb;border-radius:10px}.devices b,.devices small{display:block}.devices small{margin-top:4px;color:var(--muted)}.room-link{display:block;margin-top:16px;color:var(--primary);text-decoration:none;font-weight:700}@media(max-width:900px){.room-grid{grid-template-columns:1fr}}`]})
export class RoomsComponent{private http=inject(HttpClient);rooms=signal<Room[]>([]);devices=signal<Device[]>([]);locations=signal<Location[]>([]);showForm=signal(false);error=signal("");draft={name:"",locationId:"",kind:"REAL",capacity:4};constructor(){this.load();}load(){this.http.get<Room[]>("/api/rooms").subscribe({next:r=>this.rooms.set(r)});this.http.get<Device[]>("/api/devices").subscribe({next:d=>this.devices.set(d)});this.http.get<Location[]>("/api/locations").subscribe({next:l=>{this.locations.set(l);if(!this.draft.locationId&&l[0])this.draft.locationId=l[0].id;}});}create(){this.http.post("/api/rooms",this.draft).subscribe({next:()=>{this.showForm.set(false);this.draft.name="";this.load();},error:()=>this.error.set("Не удалось создать комнату.")});}roomDevices(id:string){return this.devices().filter(d=>d.room_id===id)}roomOnline(id:string){return this.roomDevices(id).some(d=>d.status==="ONLINE")}}
