import { Component, inject, signal } from "@angular/core";
import { DatePipe } from "@angular/common";
import { FormsModule } from "@angular/forms";
import { HttpClient } from "@angular/common/http";
import { RouterLink } from "@angular/router";
type Location={id:string;name:string}; type Room={id:string;name:string;kind:string;capacity:number;status:string;location_id:string;location_name:string}; type Device={id:string;room_id:string;name:string;type:string;status:string;last_seen:string|null;agent_id:string|null};
@Component({selector:"app-rooms",standalone:true,imports:[FormsModule,RouterLink,DatePipe],template:`
<main><aside><h1>Q <span>QUESTCONTROL</span></h1><nav><a routerLink="/">Обзор</a><a routerLink="/bookings">Бронирования</a><a class="sessions-nav" routerLink="/sessions">Сессии</a><a routerLink="/locations">Локации</a><a class="active" routerLink="/rooms">Комнаты</a><a routerLink="/cameras">Камеры</a><a routerLink="/krampus">Krampus House</a><a routerLink="/users">Пользователи</a></nav></aside>
<section><header><div><h2>Комнаты и устройства</h2><p>Состояние площадок и подключённых агентов</p></div><button (click)="toggleForm()">{{showForm()?"Закрыть":"+ Добавить комнату"}}</button></header>
@if(showForm()){<form (ngSubmit)="save()"><label>Название<input name="name" [(ngModel)]="draft.name" required></label><label>Локация<select name="location" [(ngModel)]="draft.locationId" required>@for(l of locations();track l.id){<option [value]="l.id">{{l.name}}</option>}</select></label><label>Тип<select name="kind" [(ngModel)]="draft.kind"><option value="REAL">Реальная</option><option value="VR">VR</option></select></label><label>Вместимость<input name="capacity" type="number" min="1" [(ngModel)]="draft.capacity"></label><button>{{editingId()?"Сохранить":"Создать"}}</button></form>}
@if(error()){<p class="error">{{error()}}</p>}<div class="location-groups">@for(l of locations();track l.id){<div class="location-group"><div class="location-title"><h3>{{l.name}}</h3><span>{{roomsForLocation(l.id).length}} комнат</span></div><div class="room-grid">@for(r of roomsForLocation(l.id);track r.id){<article><div class="room-head"><div><span class="eyebrow">{{r.kind}} · до {{r.capacity}} игроков</span><h3>{{r.name}}</h3></div><div class="room-actions"><span class="dot" [class.online]="roomOnline(r.id)">{{roomOnline(r.id)?"ONLINE":"OFFLINE"}}</span><button class="edit" (click)="edit(r)">Изменить</button>@if(isOwner()){<button class="danger" (click)="remove(r)">Удалить</button>}</div></div><div class="devices">@for(d of roomDevices(r.id);track d.id){<div><span><b>{{d.name}}</b><small>{{d.type}} · {{d.agent_id||"без агента"}}</small></span><span><b>{{d.status}}</b><small>{{d.last_seen?(d.last_seen|date:'HH:mm:ss'):"нет heartbeat"}}</small></span></div>}@empty{<p>Устройства не привязаны</p>}</div>@if(/krampus/i.test(r.name)){<a class="room-link" routerLink="/krampus">Открыть панель Krampus →</a>}</article>}@empty{<div class="empty compact"><b>В этой локации комнат пока нет</b></div>}</div></div>}@empty{<div class="empty"><b>Локаций пока нет</b></div>}</div></section></main>`,
styles:[`.location-groups{display:grid;gap:30px;margin-top:24px}.location-title{display:flex;align-items:center;justify-content:space-between;margin-bottom:12px}.location-title h3{margin:0;font-size:20px}.location-title span{color:var(--muted)}.room-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.room-grid>article{padding:20px;background:#fff;border:1px solid var(--line);border-radius:16px}.empty.compact{margin:0;padding:35px;grid-column:1/-1}.room-head{display:flex;justify-content:space-between}.room-head h3{margin:6px 0 18px;font-size:20px}.room-actions{display:flex;align-items:flex-start;gap:7px}.edit{padding:7px 9px;background:#eef1f6;color:#344054;box-shadow:none}.eyebrow{color:var(--muted);font-size:11px;font-weight:700}.dot{height:max-content;padding:7px 9px;border-radius:999px;background:#feecef;color:#a62938;font-size:10px;font-weight:800}.dot.online{background:#e5f8ed;color:#087443}.devices{display:grid;gap:8px}.devices>div{display:flex;justify-content:space-between;padding:12px;background:#f8f9fb;border-radius:10px}.devices b,.devices small{display:block}.devices small{margin-top:4px;color:var(--muted)}.room-link{display:block;margin-top:16px;color:var(--primary);text-decoration:none;font-weight:700}@media(max-width:900px){.room-grid{grid-template-columns:1fr}}`]})
export class RoomsComponent{private http=inject(HttpClient);rooms=signal<Room[]>([]);devices=signal<Device[]>([]);locations=signal<Location[]>([]);showForm=signal(false);editingId=signal<string|null>(null);error=signal("");draft={name:"",locationId:"",kind:"REAL",capacity:4};constructor(){this.load();}load(){this.http.get<Room[]>("/api/rooms").subscribe({next:r=>this.rooms.set(r)});this.http.get<Device[]>("/api/devices").subscribe({next:d=>this.devices.set(d)});this.http.get<Location[]>("/api/locations").subscribe({next:l=>{this.locations.set(l);if(!this.draft.locationId&&l[0])this.draft.locationId=l[0].id;}});}toggleForm(){if(this.showForm()){this.resetForm();}else{this.showForm.set(true);}}edit(room:Room){this.editingId.set(room.id);this.draft={name:room.name,locationId:room.location_id,kind:room.kind,capacity:room.capacity};this.showForm.set(true);window.scrollTo({top:0,behavior:"smooth"});}save(){const request=this.editingId()?this.http.patch(`/api/rooms/${this.editingId()}`,this.draft):this.http.post("/api/rooms",this.draft);request.subscribe({next:()=>{this.resetForm();this.load();},error:({status})=>this.error.set(status===403?"Нет доступа к выбранной локации.":"Не удалось сохранить комнату.")});}remove(room:Room){if(!confirm(`Удалить комнату «${room.name}»?`))return;this.http.delete(`/api/rooms/${room.id}`).subscribe({next:()=>this.load(),error:({status})=>this.error.set(status===409?"Комната используется в бронях, сессиях или устройствах и не может быть удалена.":"Не удалось удалить комнату.")});}isOwner(){try{return JSON.parse(atob((sessionStorage.getItem("access_token")||"").split(".")[1])).role==="OWNER"}catch{return false}}resetForm(){this.showForm.set(false);this.editingId.set(null);this.draft={name:"",locationId:this.locations()[0]?.id||"",kind:"REAL",capacity:4};}roomsForLocation(id:string){return this.rooms().filter(room=>room.location_id===id)}roomDevices(id:string){return this.devices().filter(d=>d.room_id===id)}roomOnline(id:string){return this.roomDevices(id).some(d=>d.status==="ONLINE")}}
