import { Component, inject, signal } from "@angular/core";
import { HttpClient } from "@angular/common/http";
import { AsyncPipe, DatePipe } from "@angular/common";
import { RouterLink } from "@angular/router";
@Component({selector:"app-overview",standalone:true,imports:[AsyncPipe,DatePipe,RouterLink],template:`
<main><aside><h1>Q <span>QUESTCONTROL</span></h1><nav><a class="active" routerLink="/">Обзор</a><a routerLink="/bookings">Бронирования</a><a class="sessions-nav" routerLink="/sessions">Сессии</a><a class="sessions-nav" routerLink="/work-schedules">Графики работы</a><a routerLink="/locations">Локации</a><a routerLink="/rooms">Комнаты</a><a routerLink="/cameras">Камеры</a><a routerLink="/inventory">Инвентарь</a><a routerLink="/users">Пользователи</a><a class="reception-nav" routerLink="/reception/checkin">↗ Check-in гостей</a></nav></aside>
<section><header><div><h2>Центр управления</h2><p>{{today|date:'fullDate'}}</p></div><button routerLink="/work-schedules" [queryParams]="{time:'1'}">◷ Записать время</button></header>
<a class="checkin-callout" routerLink="/bookings"><span>R</span><div><small>Ресепшен · Escapers</small><strong>Персональные ссылки check-in</strong><p>Откройте бронь и скопируйте защищённую ссылку для гостей</p></div><b>К броням →</b></a>
@if(data$|async;as data){<a class="my-shift" [class.has-shift]="data.myShifts?.length" routerLink="/work-schedules"><span class="shift-icon">{{data.myShifts?.length?'✓':'—'}}</span><div><small>Моя смена сегодня</small>@if(data.myShifts?.length){@for(shift of data.myShifts;track shift.id){<strong>{{shift.starts_at|date:'HH:mm'}}–{{shift.ends_at|date:'HH:mm'}} · {{locationLabel(shift.location_name)}}</strong><p>{{shift.responsibility}}</p>}}@else{<strong>Сегодня смены нет</strong><p>Можно спокойно планировать день.</p>}</div><b>Открыть график →</b></a><div class="cards"><article><small>Комнат</small><b>{{data.rooms.length}}</b></article><article><small>Бронирований сегодня</small><b>{{data.bookings.length}}</b></article><article><small>Устройства</small><b>{{data.deviceSummary.length}}</b></article></div>}@else{<p>Загрузка центра управления…</p>}
</section></main>`,styles:[`.reception-nav{margin-top:10px!important;border:1px solid #ff672755;color:#fff!important}.checkin-callout{display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:16px;margin:24px 0 0;padding:17px 19px;border:1px solid #303a4c;border-radius:14px;background:linear-gradient(110deg,#171d27,#26211e);color:white;text-decoration:none}.checkin-callout>span{width:42px;height:42px;display:grid;place-items:center;border:2px solid #ff6727;border-radius:10px;color:#ff6727;font-weight:800}.checkin-callout small,.checkin-callout strong,.checkin-callout p{display:block}.checkin-callout small{color:#ff8c5b;font-size:9px;text-transform:uppercase;letter-spacing:1px}.checkin-callout strong{margin:4px 0;font-size:16px}.checkin-callout p{margin:0;color:#a6afbf;font-size:10px}.checkin-callout>b{padding:10px 13px;border:1px solid #ff6727;border-radius:8px;color:#ff8c5b;font-size:10px;text-transform:uppercase}.my-shift{display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:14px;margin-top:14px;padding:15px 18px;border:1px solid #e1e5ec;border-radius:13px;background:#fff;color:#344054;text-decoration:none}.my-shift.has-shift{border-color:#a6dfbf;background:linear-gradient(110deg,#f2fbf6,#fff)}.shift-icon{display:grid;width:38px;height:38px;place-items:center;border-radius:11px;background:#eef1f6;color:#788295;font-weight:900}.has-shift .shift-icon{background:#d8f3e4;color:#087443}.my-shift small,.my-shift strong,.my-shift p{display:block}.my-shift small{color:#788295;font-size:9px;font-weight:800;text-transform:uppercase}.my-shift strong{margin-top:3px}.my-shift p{margin:2px 0 0;color:#667085;font-size:10px}.my-shift>b{color:#4f46e5;font-size:10px}@media(max-width:700px){.checkin-callout,.my-shift{grid-template-columns:auto 1fr}.checkin-callout>b,.my-shift>b{grid-column:1/-1;text-align:center}}`]})
export class OverviewComponent{private http=inject(HttpClient);today=new Date();data$=this.http.get<any>("/api/dashboard");locationLabel(name:string){return name?.replace(/_/g," ")||"Локация"}command(id:string,action:string){this.http.post(`/api/rooms/${id}/command`,{action,payload:{}}).subscribe();}}
