import { Component, inject, signal } from "@angular/core";
import { HttpClient } from "@angular/common/http";
import { AsyncPipe, DatePipe } from "@angular/common";
import { RouterLink } from "@angular/router";
@Component({selector:"app-overview",standalone:true,imports:[AsyncPipe,DatePipe,RouterLink],template:`
<main><aside><h1>Q <span>QUESTCONTROL</span></h1><nav><a class="active" routerLink="/">Обзор</a><a routerLink="/bookings">Бронирования</a><a class="sessions-nav" routerLink="/sessions">Сессии</a><a routerLink="/locations">Локации</a><a routerLink="/rooms">Комнаты</a><a routerLink="/cameras">Камеры</a><a routerLink="/users">Пользователи</a><a class="reception-nav" routerLink="/reception/checkin">↗ Check-in гостей</a></nav></aside>
<section><header><div><h2>Центр управления</h2><p>{{today|date:'fullDate'}}</p></div><button routerLink="/bookings">+ Новое бронирование</button></header>
<a class="checkin-callout" routerLink="/reception/checkin"><span>R</span><div><small>Ресепшен · Escapers St. Pölten</small><strong>Онлайн check-in гостей</strong><p>Бронирование, анкеты участников и отправка в Time to Grow</p></div><b>Открыть ↗</b></a>
@if(data$|async;as data){<div class="cards"><article><small>Комнат</small><b>{{data.rooms.length}}</b></article><article><small>Бронирований сегодня</small><b>{{data.bookings.length}}</b></article><article><small>Устройства</small><b>{{data.deviceSummary.length}}</b></article></div>
<h3>Комнаты</h3><div class="rooms">@for(room of data.rooms;track room.id){<article><strong>{{room.name}}</strong><span>{{room.kind}} · {{room.live_status||room.status}}</span><button routerLink="/rooms">Открыть комнату</button></article>}</div>}@else{<p>Загрузка центра управления…</p>}
</section></main>`,styles:[`.reception-nav{margin-top:10px!important;border:1px solid #ff672755;color:#fff!important}.checkin-callout{display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:16px;margin:24px 0 0;padding:17px 19px;border:1px solid #303a4c;border-radius:14px;background:linear-gradient(110deg,#171d27,#26211e);color:white;text-decoration:none}.checkin-callout>span{width:42px;height:42px;display:grid;place-items:center;border:2px solid #ff6727;border-radius:10px;color:#ff6727;font-weight:800}.checkin-callout small,.checkin-callout strong,.checkin-callout p{display:block}.checkin-callout small{color:#ff8c5b;font-size:9px;text-transform:uppercase;letter-spacing:1px}.checkin-callout strong{margin:4px 0;font-size:16px}.checkin-callout p{margin:0;color:#a6afbf;font-size:10px}.checkin-callout>b{padding:10px 13px;border:1px solid #ff6727;border-radius:8px;color:#ff8c5b;font-size:10px;text-transform:uppercase}@media(max-width:700px){.checkin-callout{grid-template-columns:auto 1fr}.checkin-callout>b{grid-column:1/-1;text-align:center}}`]})
export class OverviewComponent{private http=inject(HttpClient);today=new Date();data$=this.http.get<any>("/api/dashboard");command(id:string,action:string){this.http.post(`/api/rooms/${id}/command`,{action,payload:{}}).subscribe();}}
